### ISSUE TITLE
[Bug] git checkout in typescript.yml failing for forked repos

### ISSUE THREAD

**Issue by lorensr** [temporalio/sdk-features#23]
I think this is failing:

https://github.com/temporalio/sdk-features/blob/main/.github/workflows/typescript.yaml#L33

When running on a fork, like this:

[sdk-features-tests / build-ts](https://github.com/temporalio/sdk-typescript/runs/5308260603?check_suite_focus=true#logs)

Perhaps this would fix:

https://github.com/actions/checkout/issues/455#issuecomment-792228083

**Comment by Sushisource** [comment]
@lorensr This is already fixed in https://github.com/temporalio/sdk-features/pull/21 -- I think probably wherever you saw this just wasn't using latest HEAD of the TS repo. Reopen if I'm wrong.

**Comment by Sushisource** [comment]
NM. Is a real bug with _some_ forks
