### ISSUE TITLE
[Feature Request] Compile and package gRPC client for operator service for all SDKs

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-features#28]
OperatorService was added here:
https://github.com/temporalio/api/tree/master/temporal/api/operatorservice/v1

- [x] TS
- [x] Java
- [x] Go https://github.com/temporalio/sdk-go/issues/896
- [x] Python temporalio/sdk-python/issues/93
- [x] PHP temporalio/sdk-php/issues/229

**Comment by bergundy** [comment]
@Sushisource is exposing the service from Core so it can be used in Python

**Comment by bergundy** [comment]
Confirmed this is available for Go: https://github.com/temporalio/api-go/tree/master/operatorservice/v1

**Comment by wolfy-j** [comment]
PHP should already have it.

**Comment by cretz** [comment]
@bergundy - We still need to expose this in Go same as we do for `Client.WorkflowService()`

**Comment by bergundy** [comment]
Unchecked for Go, makes sense, thanks.

**Comment by bergundy** [comment]
@cretz this is done, right?
