### ISSUE TITLE
[Feature Request] Update workflow time when processing queries

### ISSUE THREAD

**Issue by bergundy** [temporalio/sdk-features#31]
### Is your feature request related to a problem? Please describe.

Sometimes it's required to get the Date at the time a query is processed as opposed to the last processed workflow task's time.
For example this query will always return the same result:

```ts
setHandler(timerSettingsQuery, () => {
  const deadlineMs = timer.getDeadline();
  return { sleepIntervalMs: timer.sleepMs, timeLeftMs: deadlineMs - Date.now(), deadlineMs: deadlineMs };
});
```

### Describe the solution you'd like

Update workflow time before processing queries (and possibly immediately reset back to workflow time)
Special care should be taken not to trigger any `condition`s (`Workflow.await`).

**Comment by cretz** [comment]
Hrmm, the idea that anything in a query can be different for each invocation of the same query is a bit concerning. I am not sure we should support one worker giving a different result to a query than another worker (or replayer). I am not convinced we should support this.

Basically with this change we've now said that queries aren't idempotent (in the strict sense that for the same input they get the same output). For this specific use case, the deadline can be returned and the caller can use their notion of "now" to do any calculations. While that may be different than the worker's, both may be different than the server's which is what really matters here. No worker-specific anything should affect a query's output.

**Comment by bergundy** [comment]
Queries are different than other workflow events, they don't need to be deterministic. I initially argued with @mfateev (who originally suggested this feature) for the same reasons both of you bring up here but after thinking about it I don't see a reason why we shouldn't support this.

I agree the handler above could be implemented on the caller side like @Sushisource points out but why not in the workflow?
As for the replayer you've mentioned @cretz, do the Go or Java replayers support running additional queries after replay? That could be a useful feature.

**Comment by bergundy** [comment]
I think this would mostly be relevant to TS where the wall clock isn’t available. Since user might want the workflow time in some cases, right now I think the right thing is to expose system time in the unsafe part of WorkflowInfo, it could be useful in other situations like tracing.

**Comment by bergundy** [comment]
Closing in favor of the linked TS issue, not needed for non-sandboxed runtimes.
